# Generated by Django 4.2.9 on 2024-06-29 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 29, 17, 2, 47, 678742))),
                ('comments', models.TextField()),
                ('author', models.CharField(max_length=150)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 6, 29, 17, 2, 47, 678742))),
            ],
        ),
    ]
