# Generated by Django 4.2.9 on 2024-06-29 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_commnets_count_alter_blog_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='commnets_count',
            new_name='comments_count',
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 6, 29, 17, 43, 12, 293162)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 29, 17, 43, 12, 293162)),
        ),
    ]
