# Generated by Django 4.2.9 on 2024-07-02 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_created_at_alter_blog_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 2, 17, 7, 25, 754895)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 17, 7, 25, 754895)),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 17, 7, 25, 755899)),
        ),
    ]
