# Generated by Django 4.2.9 on 2024-07-02 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blog_created_at_alter_blog_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 2, 17, 20, 47, 2082)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 17, 20, 47, 2082)),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 2, 17, 20, 47, 3463)),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
